### ISSUE TITLE
Remove data bundles from swagger.json

### ISSUE THREAD

**Issue by david4096** [DataBiosphere/dos-azul-lambda#15] opened 2018-04-26 01:16 UTC
This service provides a subset of the DOS, which should be reflected in the swagger it hosts.

To close this remove the unused endpoints (data bundles) and add to this repo. Added goal is to load the swagger into the chalicelib folder instead of fetching from a URL.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DAL-3)
┆Project Name: dos-azul-lambda
┆Issue Number: DAL-3
┆Epic: One point ohh

**Comment by cricketsloan** [comment] 2018-07-20 02:10
➤ David Steinberg commented:

This is a relatively low priority change and requires a lot of hand curation. The endpoints should return unimplemented responses properly, though.

**Comment by natanlao** [comment] 2018-08-30 17:30
Duplicate of #29
Closed by #97

**Closed by natanlao** 2018-08-30 17:30 UTC
