### ISSUE TITLE
Auth handler breaks with 1.3.0

### ISSUE THREAD

**Issue by david4096** [DataBiosphere/dos-azul-lambda#20] opened 2018-05-25 04:21 UTC
Chalice 1.3.0 seems to cause an error trying to authenticate. May need to recreate configuration.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DAL-11)
┆Project Name: dos-azul-lambda
┆Issue Number: DAL-11
┆Epic: DAL One point ohh

**Comment by david4096** [comment] 2018-07-19 23:54
This may have been an intermittent problem with chalice. Should try removing the version requirement and rerunning. @natanlao I think this was about the location of the aws credentials.

**Comment by natanlao** [comment] 2018-07-19 23:56
Ah yeah - I fixed that particular problem by adding my credentials to `~/.aws/credentials` in addition to `~/.aws/config`. I'll investigate further

**Comment by natanlao** [comment] 2018-07-23 17:10
How did you come across the error? Do you have a traceback?

**Comment by natanlao** [comment] 2018-08-02 19:32
Is there any utility to specifying `chalice==1.2.2` in the first place? dos-azul-lambda itself doesn't use chalice internally. If we're able to deploy with later versions of chalice, I don't think this is in the scope of the project.

**Comment by natanlao** [comment] 2018-08-09 20:55
The latest version of Chalice is 1.6.0. I think it is reasonable to ensure that deployment works with Chalice 1.6.0 in order to close this ticket.

**Comment by natanlao** [comment] 2018-08-09 21:01
I am able to reproduce this on 4010e3b.

``` $ chalice --debug deploy
2018-08-09 13:57:58,692 - pip.utils - DEBUG - lzma module is not available
2018-08-09 13:57:58,692 - pip.vcs - DEBUG - Registered VCS backend: git
2018-08-09 13:57:58,719 - pip.vcs - DEBUG - Registered VCS backend: hg
2018-08-09 13:57:58,748 - pip.vcs - DEBUG - Registered VCS backend: svn
2018-08-09 13:57:58,749 - pip.vcs - DEBUG - Registered VCS backend: bzr
2018-08-09 13:57:58,826 - boto - DEBUG - Retrieving credentials from metadata server.
2018-08-09 13:57:59,829 - boto - ERROR - Caught exception reading instance data
Traceback (most recent call last):
  File "/home/natan/cgl/dos-azul-lambda/venv/local/lib/python2.7/site-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
2018-08-09 13:57:59,835 - boto - ERROR - Unable to read instance data, giving up
Traceback (most recent call last):
  File "/home/natan/cgl/dos-azul-lambda/venv/local/lib/python2.7/site-packages/chalice/cli/__init__.py", line 384, in main
    return cli(obj={})
  File "/home/natan/cgl/dos-azul-lambda/venv/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/natan/cgl/dos-azul-lambda/venv/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/natan/cgl/dos-azul-lambda/venv/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/natan/cgl/dos-azul-lambda/venv/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/natan/cgl/dos-azul-lambda/venv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/natan/cgl/dos-azul-lambda/venv/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/natan/cgl/dos-azul-lambda/venv/local/lib/python2.7/site-packages/chalice/cli/__init__.py", line 166, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/home/natan/cgl/dos-azul-lambda/venv/local/lib/python2.7/site-packages/chalice/deploy/deployer.py", line 346, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/home/natan/cgl/dos-azul-lambda/venv/local/lib/python2.7/site-packages/chalice/deploy/deployer.py", line 352, in _deploy
    self._validate_config(config)
  File "/home/natan/cgl/dos-azul-lambda/venv/local/lib/python2.7/site-packages/chalice/deploy/deployer.py", line 375, in _validate_config
    validate_configuration(config)
  File "/home/natan/cgl/dos-azul-lambda/venv/local/lib/python2.7/site-packages/chalice/deploy/validate.py", line 20, in validate_configuration
    routes = config.chalice_app.routes
  File "/home/natan/cgl/dos-azul-lambda/venv/local/lib/python2.7/site-packages/chalice/config.py", line 143, in chalice_app
    app = v()
  File "/home/natan/cgl/dos-azul-lambda/venv/local/lib/python2.7/site-packages/chalice/cli/factory.py", line 186, in load_chalice_app
    app = importlib.import_module('app')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/natan/cgl/dos-azul-lambda/app.py", line 97, in <module>
    region=es_region, host=es_host, is_secure=False)
  File "/home/natan/cgl/dos-azul-lambda/app.py", line 68, in __init__
    super(ESConnection, self).__init__(**kwargs)
  File "/home/natan/cgl/dos-azul-lambda/venv/local/lib/python2.7/site-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/home/natan/cgl/dos-azul-lambda/venv/local/lib/python2.7/site-packages/boto/auth.py", line 1021, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials
```

**Comment by natanlao** [comment] 2018-08-10 00:12
I can reproduce this on `chalice==1.6.0`

**Comment by natanlao** [comment] 2018-08-10 00:48
`chalice deploy` and `chalice local` work if `AWS_SECRET_ACCESS_KEY` and `AWS_ACCESS_KEY_ID` are specified as environment variables. I've identified the change in aws/chalice as commit 8b2b58da84f08f3d18678dedaa647a7614a3ee17

**Comment by natanlao** [comment] 2018-08-10 18:09
I've found the cause of the bug.

* Commit [8b2b5](https://github.com/aws/chalice/commit/8b2b58da84f08f3d18678dedaa647a7614a3ee17) in aws/chalice (part of version 1.3.0) changed Chalice's behavior to load environment variables specified in `.chalice/config.json` before instantiation of `Chalice()` (as opposed to only loading those variables after instantiation).
* The `HOME` environment variable is specified as `/tmp` in [config.json](https://github.com/DataBiosphere/dos-azul-lambda/blob/4010e3b56c08f92f935d94141696c3ddf6082f61/.chalice/config.json#L29).
* Boto looks for AWS credentials in `$HOME/.aws/credentials` and `$HOME/.aws/config`.
* Since `/tmp/.aws/credentials` and `/tmp/.aws/config` doesn't (or at least isn't supposed to) exist, boto can't find valid AWS credentials.
* Since boto can't find valid AWS credentials, it can't [authenticate](https://github.com/DataBiosphere/dos-azul-lambda/blob/4010e3b56c08f92f935d94141696c3ddf6082f61/app.py#L96) to AWS/ElasticSearch, causing the traceback above:

        File "/home/natan/cgl/dos-azul-lambda/app.py", line 97, in <module>
          region=es_region, host=es_host, is_secure=False)

* This is also why `chalice local` and `chalice deploy` work if credentials are specified as environment variables.

**Closed** 2018-08-10 22:49 UTC
Labels: in progress
